const YahooFinance = require('yahoo-finance2').default;
const yahooFinance = new YahooFinance({ suppressNotices: ['yahooSurvey', 'ripHistorical'] });

// In-memory cache to prevent Yahoo Finance rate-limiting (HTTP 429)
const priceCache = new Map();
const CACHE_DURATION_MS = 2 * 60 * 1000; // 2 minutes — prevents Yahoo Finance 429 rate-limit block

const getStockPrice = async (symbol) => {
    if (!symbol) return null;
    const querySymbol = symbol; // Trust the symbol exactly as passed
    
    // Check Cache first (30 second cache to prevent rate-limiting)
    if (priceCache.has(querySymbol)) {
        const cached = priceCache.get(querySymbol);
        if (Date.now() - cached.timestamp < CACHE_DURATION_MS) {
            return cached.price;
        }
    }

    // --- PRIMARY: Yahoo Finance (Reliable, correct prices) ---
    try {
        const timeout = new Promise((_, reject) => setTimeout(() => reject(new Error('Yahoo Timeout')), 5000));
        const quote = await Promise.race([yahooFinance.quote(querySymbol), timeout]);
        const price = quote ? quote.regularMarketPrice : null;
        if (price && price > 0) {
            priceCache.set(querySymbol, { price, timestamp: Date.now() });
            console.log(`[Yahoo] ${symbol} = ₹${price}`);
            return price;
        }
    } catch (yhError) {
        console.warn(`[Yahoo] Failed for ${symbol}: ${yhError.message}. Trying Groww...`);
    }

    // --- FALLBACK 1: Groww API (Highly reliable for NSE stocks) ---
    try {
        const cleanSymbol = symbol.split('.')[0];
        const growwUrl = `https://groww.in/v1/api/stocks_data/v1/tr_live_prices/exchange/NSE/segment/CASH/${cleanSymbol}/latest`;
        
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 4000);
        const response = await fetch(growwUrl, { signal: controller.signal });
        clearTimeout(timeout);
        
        if (response.ok) {
            const data = await response.json();
            const price = data.ltp || data.close;
            if (price && price > 0) {
                priceCache.set(querySymbol, { price, timestamp: Date.now() });
                console.log(`[Groww] ${symbol} = ₹${price}`);
                return price;
            }
        }
    } catch (growwError) {
        console.warn(`[Groww] Failed for ${symbol}: ${growwError.message}. Trying Google...`);
    }

    // --- FALLBACK 2: Google Finance HTML ---
    try {
        let exchanges = ['NSE'];
        if (symbol.endsWith('.BO')) exchanges = ['BOM'];
        else if (!symbol.endsWith('.NS') && !symbol.endsWith('.BO')) exchanges = ['NYSE', 'NASDAQ'];
        
        const gfSymbol = symbol.split('.')[0];
        
        for (const exchange of exchanges) {
            const controller = new AbortController();
            const gfTimeout = setTimeout(() => controller.abort(), 4000);
            try {
                const response = await fetch(`https://www.google.com/finance/quote/${gfSymbol}:${exchange}`, { 
                    headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' },
                    signal: controller.signal 
                });
                clearTimeout(gfTimeout);
                
                if (response.ok) {
                    const html = await response.text();
                    const match = html.match(/class="YMlKec fxKbKc">([^<]+)<\/div>/);
                    if (match && match[1]) {
                        const parsedPrice = parseFloat(match[1].replace(/[^0-9.]/g, ''));
                        if (!isNaN(parsedPrice) && parsedPrice > 0) {
                            priceCache.set(querySymbol, { price: parsedPrice, timestamp: Date.now() });
                            console.log(`[GoogleFinance] ${symbol} = ₹${parsedPrice} (via ${exchange})`);
                            return parsedPrice;
                        }
                    }
                }
            } catch (e) {
                clearTimeout(gfTimeout);
            }
        }
    } catch (gfError) {
        console.warn(`[GoogleFinance] Failed for ${symbol}: ${gfError.message}`);
    }

    // Last Resort: Return stale cache
    if (priceCache.has(querySymbol)) {
        console.warn(`[Cache] Using stale price for ${symbol}`);
        return priceCache.get(querySymbol).price;
    }

    console.error(`[Price] All sources failed for ${symbol}. Returning null.`);
    return null;
};


const searchSymbol = async (query) => {
    try {
        // Strip extensions to force a fuzzy search on the base company name/ticker
        const cleanQuery = query.trim().toUpperCase().replace('.NS', '').replace('.BO', '');
        // Step 1: Explicitly check for the Indian NSE stock first
        const nseQuery = `${cleanQuery}.NS`;
        let results = await yahooFinance.search(nseQuery);
        
        if (results.quotes && results.quotes.length > 0) {
            const exactNseMatch = results.quotes.find(q => q.symbol === nseQuery);
            if (exactNseMatch) return exactNseMatch.symbol;
        }

        // Step 2: Fallback to global search if NSE stock not found
        results = await yahooFinance.search(cleanQuery);
        
        if (results.quotes && results.quotes.length > 0) {
            // Prioritize Indian stock exchanges (.NS or .BO) just in case
            const indianStock = results.quotes.find(q => q.symbol && (q.symbol.endsWith('.NS') || q.symbol.endsWith('.BO')));
            if (indianStock) return indianStock.symbol;
            
            // Fallback to the top result if it's not an Indian stock
            const firstValidStock = results.quotes.find(q => q.symbol);
            if (firstValidStock) return firstValidStock.symbol;
        }
        
        // If search completely fails, fallback to formatting it manually
        let sym = query.trim().toUpperCase().replace(/\s+/g, '');
        sym = sym.replace('.BO', '.NS');
        if (!sym.endsWith('.NS')) sym += '.NS';
        return sym;
    } catch (error) {
        console.error(`Search failed for ${query}:`, error);
        // Fallback manually
        let sym = query.trim().toUpperCase().replace(/\s+/g, '');
        sym = sym.replace('.BO', '.NS');
        if (!sym.endsWith('.NS')) sym += '.NS';
        return sym;
    }
};

const getMarketMovers = async () => {
    try {
        // Enforce a strict 3-second timeout to prevent Yahoo from hanging the server
        // Add .catch() to prevent background Unhandled Rejection crashes when the abandoned promise finally fails
        const fetchScreener = yahooFinance.screener({ scrIds: 'day_gainers', count: 10, region: 'IN' }).catch(e => null);
        const fetchLosers = yahooFinance.screener({ scrIds: 'day_losers', count: 10, region: 'IN' }).catch(e => null);
        
        const timeout = new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), 3000));
        
        const gainersResult = await Promise.race([fetchScreener, timeout]);
        const losersResult = await Promise.race([fetchLosers, timeout]);
        
        if (!gainersResult || !losersResult || !gainersResult.quotes[0]?.symbol.endsWith('.NS')) {
            throw new Error("Yahoo Rate Limited or Non-IN Stocks - Booting Fallback");
        }

        const mapQuote = (q) => ({
            symbol: q.symbol,
            name: q.shortName || q.longName,
            price: q.regularMarketPrice,
            changePercent: q.regularMarketChangePercent
        });

        return {
            gainers: (gainersResult && gainersResult.quotes) ? gainersResult.quotes.map(mapQuote) : [],
            losers: (losersResult && losersResult.quotes) ? losersResult.quotes.map(mapQuote) : []
        };
    } catch (error) {
        console.error("Yahoo Screener Blocked/Timed Out. Booting up Fail-Safe Fallback...");
        // Bypassing Yahoo Block: Massive pool of 100 High-Beta/Volatile Indian stocks (Strategy B)
                const fallbackData = [
{ symbol: '20MICRONS.NS', name: '20MICRONS' },
{ symbol: '21STCENMGM.NS', name: '21STCENMGM' },
{ symbol: '360ONE.NS', name: '360ONE' },
{ symbol: '3BBLACKBIO.NS', name: '3BBLACKBIO' },
{ symbol: '3IINFOLTD.NS', name: '3IINFOLTD' },
{ symbol: '3MINDIA.NS', name: '3MINDIA' },
{ symbol: '3PLAND.NS', name: '3PLAND' },
{ symbol: '5PAISA.NS', name: '5PAISA' },
{ symbol: '63MOONS.NS', name: '63MOONS' },
{ symbol: 'A2ZINFRA.NS', name: 'A2ZINFRA' },
{ symbol: 'AAATECH.NS', name: 'AAATECH' },
{ symbol: 'AADHARHFC.NS', name: 'AADHARHFC' },
{ symbol: 'AAKASH.NS', name: 'AAKASH' },
{ symbol: 'AAREYDRUGS.NS', name: 'AAREYDRUGS' },
{ symbol: 'AARNAV.NS', name: 'AARNAV' },
{ symbol: 'AARON.NS', name: 'AARON' },
{ symbol: 'AARTECH.NS', name: 'AARTECH' },
{ symbol: 'AARTIDRUGS.NS', name: 'AARTIDRUGS' },
{ symbol: 'AARTIIND.NS', name: 'AARTIIND' },
{ symbol: 'AARTIPHARM.NS', name: 'AARTIPHARM' },
{ symbol: 'AARTISURF.NS', name: 'AARTISURF' },
{ symbol: 'AARVI.NS', name: 'AARVI' },
{ symbol: 'AASTHA.NS', name: 'AASTHA' },
{ symbol: 'AAVAS.NS', name: 'AAVAS' },
{ symbol: 'ABAN.NS', name: 'ABAN' },
{ symbol: 'ABANSENT.NS', name: 'ABANSENT' },
{ symbol: 'ABB.NS', name: 'ABB' },
{ symbol: 'ABBOTINDIA.NS', name: 'ABBOTINDIA' },
{ symbol: 'ABCAPITAL.NS', name: 'ABCAPITAL' },
{ symbol: 'ABCOTS.NS', name: 'ABCOTS' },
{ symbol: 'ABDL.NS', name: 'ABDL' },
{ symbol: 'ABFRL.NS', name: 'ABFRL' },
{ symbol: 'ABINFRA.NS', name: 'ABINFRA' },
{ symbol: 'ABLBL.NS', name: 'ABLBL' },
{ symbol: 'ABMINTLLTD.NS', name: 'ABMINTLLTD' },
{ symbol: 'ABMKNO.NS', name: 'ABMKNO' },
{ symbol: 'ABREL.NS', name: 'ABREL' },
{ symbol: 'ABSLAMC.NS', name: 'ABSLAMC' },
{ symbol: 'ACC.NS', name: 'ACC' },
{ symbol: 'ACCELYA.NS', name: 'ACCELYA' },
{ symbol: 'ACCURACY.NS', name: 'ACCURACY' },
{ symbol: 'ACE.NS', name: 'ACE' },
{ symbol: 'ACEINTEG.NS', name: 'ACEINTEG' },
{ symbol: 'ACI.NS', name: 'ACI' },
{ symbol: 'ACL.NS', name: 'ACL' },
{ symbol: 'ACMESOLAR.NS', name: 'ACMESOLAR' },
{ symbol: 'ACSTECH.NS', name: 'ACSTECH' },
{ symbol: 'ACUTAAS.NS', name: 'ACUTAAS' },
{ symbol: 'ADANIENSOL.NS', name: 'ADANIENSOL' },
{ symbol: 'ADANIENT.NS', name: 'ADANIENT' },
{ symbol: 'ADANIGREEN.NS', name: 'ADANIGREEN' },
{ symbol: 'ADANIPORTS.NS', name: 'ADANIPORTS' },
{ symbol: 'ADANIPOWER.NS', name: 'ADANIPOWER' },
{ symbol: 'ADFFOODS.NS', name: 'ADFFOODS' },
{ symbol: 'ADL.NS', name: 'ADL' },
{ symbol: 'ADOR.NS', name: 'ADOR' },
{ symbol: 'ADROITINFO.NS', name: 'ADROITINFO' },
{ symbol: 'ADSL.NS', name: 'ADSL' },
{ symbol: 'ADVAIT.NS', name: 'ADVAIT' },
{ symbol: 'ADVANCE.NS', name: 'ADVANCE' },
{ symbol: 'ADVANIHOTR.NS', name: 'ADVANIHOTR' },
{ symbol: 'ADVENTHTL.NS', name: 'ADVENTHTL' },
{ symbol: 'ADVENZYMES.NS', name: 'ADVENZYMES' },
{ symbol: 'AEGISLOG.NS', name: 'AEGISLOG' },
{ symbol: 'AEGISVOPAK.NS', name: 'AEGISVOPAK' },
{ symbol: 'AEPL.NS', name: 'AEPL' },
{ symbol: 'AEQUS.NS', name: 'AEQUS' },
{ symbol: 'AEROENTER.NS', name: 'AEROENTER' },
{ symbol: 'AEROFLEX.NS', name: 'AEROFLEX' },
{ symbol: 'AERONEU.NS', name: 'AERONEU' },
{ symbol: 'AEROPLANE.NS', name: 'AEROPLANE' },
{ symbol: 'AETHER.NS', name: 'AETHER' },
{ symbol: 'AFCONS.NS', name: 'AFCONS' },
{ symbol: 'AFFLE.NS', name: 'AFFLE' },
{ symbol: 'AFFORDABLE.NS', name: 'AFFORDABLE' },
{ symbol: 'AFIL.NS', name: 'AFIL' },
{ symbol: 'AFSL.NS', name: 'AFSL' },
{ symbol: 'AGARIND.NS', name: 'AGARIND' },
{ symbol: 'AGARWALEYE.NS', name: 'AGARWALEYE' },
{ symbol: 'AGI.NS', name: 'AGI' },
{ symbol: 'AGIIL.NS', name: 'AGIIL' },
{ symbol: 'AGL.NS', name: 'AGL' },
{ symbol: 'AGRITECH.NS', name: 'AGRITECH' },
{ symbol: 'AGROPHOS.NS', name: 'AGROPHOS' },
{ symbol: 'AHCL.NS', name: 'AHCL' },
{ symbol: 'AHLADA.NS', name: 'AHLADA' },
{ symbol: 'AHLEAST.NS', name: 'AHLEAST' },
{ symbol: 'AHLUCONT.NS', name: 'AHLUCONT' },
{ symbol: 'AHLWEST.NS', name: 'AHLWEST' },
{ symbol: 'AIAENG.NS', name: 'AIAENG' },
{ symbol: 'AIIL.NS', name: 'AIIL' },
{ symbol: 'AIRAN.NS', name: 'AIRAN' },
{ symbol: 'AIROLAM.NS', name: 'AIROLAM' },
{ symbol: 'AJANTPHARM.NS', name: 'AJANTPHARM' },
{ symbol: 'AJAXENGG.NS', name: 'AJAXENGG' },
{ symbol: 'AJMERA.NS', name: 'AJMERA' },
{ symbol: 'AJOONI.NS', name: 'AJOONI' },
{ symbol: 'AKASH.NS', name: 'AKASH' },
{ symbol: 'AKCAPIT.NS', name: 'AKCAPIT' },
{ symbol: 'AKG.NS', name: 'AKG' },
{ symbol: 'AKI.NS', name: 'AKI' },
{ symbol: 'AKSHAR.NS', name: 'AKSHAR' },
{ symbol: 'AKSHARCHEM.NS', name: 'AKSHARCHEM' },
{ symbol: 'AKSHOPTFBR.NS', name: 'AKSHOPTFBR' },
{ symbol: 'AKUMS.NS', name: 'AKUMS' },
{ symbol: 'ALANKIT.NS', name: 'ALANKIT' },
{ symbol: 'ALBERTDAVD.NS', name: 'ALBERTDAVD' },
{ symbol: 'ALEMBICLTD.NS', name: 'ALEMBICLTD' },
{ symbol: 'ALGOQUANT.NS', name: 'ALGOQUANT' },
{ symbol: 'ALICON.NS', name: 'ALICON' },
{ symbol: 'ALIVUS.NS', name: 'ALIVUS' },
{ symbol: 'ALKALI.NS', name: 'ALKALI' },
{ symbol: 'ALKEM.NS', name: 'ALKEM' },
{ symbol: 'ALKYLAMINE.NS', name: 'ALKYLAMINE' },
{ symbol: 'ALLCARGO.NS', name: 'ALLCARGO' },
{ symbol: 'ALLDIGI.NS', name: 'ALLDIGI' },
{ symbol: 'ALLTIME.NS', name: 'ALLTIME' },
{ symbol: 'ALMONDZ.NS', name: 'ALMONDZ' },
{ symbol: 'ALOKINDS.NS', name: 'ALOKINDS' },
{ symbol: 'ALPA.NS', name: 'ALPA' },
{ symbol: 'ALPHAGEO.NS', name: 'ALPHAGEO' },
{ symbol: 'ALPINETEX.NS', name: 'ALPINETEX' },
{ symbol: 'AMAGI.NS', name: 'AMAGI' },
{ symbol: 'AMANTA.NS', name: 'AMANTA' },
{ symbol: 'AMBALALSA.NS', name: 'AMBALALSA' },
{ symbol: 'AMBER.NS', name: 'AMBER' },
{ symbol: 'AMBICAAGAR.NS', name: 'AMBICAAGAR' },
{ symbol: 'AMBIKCO.NS', name: 'AMBIKCO' },
{ symbol: 'AMBUJACEM.NS', name: 'AMBUJACEM' },
{ symbol: 'AMDIND.NS', name: 'AMDIND' },
{ symbol: 'AMJLAND.NS', name: 'AMJLAND' },
{ symbol: 'AMNPLST.NS', name: 'AMNPLST' },
{ symbol: 'AMRUTANJAN.NS', name: 'AMRUTANJAN' },
{ symbol: 'ANANDRATHI.NS', name: 'ANANDRATHI' },
{ symbol: 'ANANTRAJ.NS', name: 'ANANTRAJ' },
{ symbol: 'ANDHRAPAP.NS', name: 'ANDHRAPAP' },
{ symbol: 'ANDHRSUGAR.NS', name: 'ANDHRSUGAR' },
{ symbol: 'ANGELONE.NS', name: 'ANGELONE' },
{ symbol: 'ANIKINDS.NS', name: 'ANIKINDS' },
{ symbol: 'ANKITMETAL.NS', name: 'ANKITMETAL' },
{ symbol: 'ANMOL.NS', name: 'ANMOL' },
{ symbol: 'ANSALAPI.NS', name: 'ANSALAPI' },
{ symbol: 'ANTELOPUS.NS', name: 'ANTELOPUS' },
{ symbol: 'ANTGRAPHIC.NS', name: 'ANTGRAPHIC' },
{ symbol: 'ANTHEM.NS', name: 'ANTHEM' },
{ symbol: 'ANUHPHR.NS', name: 'ANUHPHR' },
{ symbol: 'ANUP.NS', name: 'ANUP' },
{ symbol: 'ANURAS.NS', name: 'ANURAS' },
{ symbol: 'APARINDS.NS', name: 'APARINDS' },
{ symbol: 'APCL.NS', name: 'APCL' },
{ symbol: 'APCOTEXIND.NS', name: 'APCOTEXIND' },
{ symbol: 'APEX.NS', name: 'APEX' },
{ symbol: 'APLAPOLLO.NS', name: 'APLAPOLLO' },
{ symbol: 'APLLTD.NS', name: 'APLLTD' },
{ symbol: 'APOLLO.NS', name: 'APOLLO' },
{ symbol: 'APOLLOHOSP.NS', name: 'APOLLOHOSP' },
{ symbol: 'APOLLOPIPE.NS', name: 'APOLLOPIPE' },
{ symbol: 'APOLLOTYRE.NS', name: 'APOLLOTYRE' },
{ symbol: 'APOLSINHOT.NS', name: 'APOLSINHOT' },
{ symbol: 'APTECHT.NS', name: 'APTECHT' },
{ symbol: 'APTUS.NS', name: 'APTUS' },
{ symbol: 'AQYLON.NS', name: 'AQYLON' },
{ symbol: 'ARCHIDPLY.NS', name: 'ARCHIDPLY' },
{ symbol: 'ARCHIES.NS', name: 'ARCHIES' },
{ symbol: 'ARE&M.NS', name: 'ARE&M' },
{ symbol: 'ARENTERP.NS', name: 'ARENTERP' },
{ symbol: 'ARFIN.NS', name: 'ARFIN' },
{ symbol: 'ARIES.NS', name: 'ARIES' },
{ symbol: 'ARIHANT.NS', name: 'ARIHANT' },
{ symbol: 'ARIHANTCAP.NS', name: 'ARIHANTCAP' },
{ symbol: 'ARIHANTSUP.NS', name: 'ARIHANTSUP' },
{ symbol: 'ARIS.NS', name: 'ARIS' },
{ symbol: 'ARKADE.NS', name: 'ARKADE' },
{ symbol: 'ARMANFIN.NS', name: 'ARMANFIN' },
{ symbol: 'AROGRANITE.NS', name: 'AROGRANITE' },
{ symbol: 'ARROWGREEN.NS', name: 'ARROWGREEN' },
{ symbol: 'ARSHIYA.NS', name: 'ARSHIYA' },
{ symbol: 'ARSSBL.NS', name: 'ARSSBL' },
{ symbol: 'ARTEMISMED.NS', name: 'ARTEMISMED' },
{ symbol: 'ARTNIRMAN.NS', name: 'ARTNIRMAN' },
{ symbol: 'ARVEE.NS', name: 'ARVEE' },
{ symbol: 'ARVIND.NS', name: 'ARVIND' },
{ symbol: 'ARVINDFASN.NS', name: 'ARVINDFASN' },
{ symbol: 'ARVSMART.NS', name: 'ARVSMART' },
{ symbol: 'ASAHIINDIA.NS', name: 'ASAHIINDIA' },
{ symbol: 'ASAHISONG.NS', name: 'ASAHISONG' },
{ symbol: 'ASAL.NS', name: 'ASAL' },
{ symbol: 'ASALCBR.NS', name: 'ASALCBR' },
{ symbol: 'ASHAPURMIN.NS', name: 'ASHAPURMIN' },
{ symbol: 'ASHIANA.NS', name: 'ASHIANA' },
{ symbol: 'ASHIKA.NS', name: 'ASHIKA' },
{ symbol: 'ASHIMASYN.NS', name: 'ASHIMASYN' },
{ symbol: 'ASHOKA.NS', name: 'ASHOKA' },
{ symbol: 'ASHOKAMET.NS', name: 'ASHOKAMET' },
{ symbol: 'ASHOKLEY.NS', name: 'ASHOKLEY' },
{ symbol: 'ASIANENE.NS', name: 'ASIANENE' },
{ symbol: 'ASIANHOTNR.NS', name: 'ASIANHOTNR' },
{ symbol: 'ASIANPAINT.NS', name: 'ASIANPAINT' },
{ symbol: 'ASIANTILES.NS', name: 'ASIANTILES' },
{ symbol: 'ASKAUTOLTD.NS', name: 'ASKAUTOLTD' },
{ symbol: 'ASMS.NS', name: 'ASMS' },
{ symbol: 'ASPINWALL.NS', name: 'ASPINWALL' },
{ symbol: 'ASTAR.NS', name: 'ASTAR' },
{ symbol: 'ASTEC.NS', name: 'ASTEC' },
{ symbol: 'ASTERDM.NS', name: 'ASTERDM' },
{ symbol: 'ASTRAL.NS', name: 'ASTRAL' },
{ symbol: 'ASTRAMICRO.NS', name: 'ASTRAMICRO' },
{ symbol: 'ASTRAZEN.NS', name: 'ASTRAZEN' },
{ symbol: 'ASTRON.NS', name: 'ASTRON' },
{ symbol: 'ATALREAL.NS', name: 'ATALREAL' },
{ symbol: 'ATAM.NS', name: 'ATAM' },
{ symbol: 'ATGL.NS', name: 'ATGL' },
{ symbol: 'ATHERENERG.NS', name: 'ATHERENERG' },
{ symbol: 'ATL.NS', name: 'ATL' },
{ symbol: 'ATLANTAA.NS', name: 'ATLANTAA' },
{ symbol: 'ATLANTAELE.NS', name: 'ATLANTAELE' },
{ symbol: 'ATLASCYCLE.NS', name: 'ATLASCYCLE' },
{ symbol: 'ATUL.NS', name: 'ATUL' },
{ symbol: 'ATULAUTO.NS', name: 'ATULAUTO' },
{ symbol: 'AUBANK.NS', name: 'AUBANK' },
{ symbol: 'AURIONPRO.NS', name: 'AURIONPRO' },
{ symbol: 'AUROPHARMA.NS', name: 'AUROPHARMA' },
{ symbol: 'AURUM.NS', name: 'AURUM' },
{ symbol: 'AURUS.NS', name: 'AURUS' },
{ symbol: 'AUSOMENT.NS', name: 'AUSOMENT' },
{ symbol: 'AUTOAXLES.NS', name: 'AUTOAXLES' },
{ symbol: 'AUTOIND.NS', name: 'AUTOIND' },
{ symbol: 'AVADHSUGAR.NS', name: 'AVADHSUGAR' },
{ symbol: 'AVALON.NS', name: 'AVALON' },
{ symbol: 'AVANTEL.NS', name: 'AVANTEL' },
{ symbol: 'AVANTIFEED.NS', name: 'AVANTIFEED' },
{ symbol: 'AVG.NS', name: 'AVG' },
{ symbol: 'AVL.NS', name: 'AVL' },
{ symbol: 'AVONMORE.NS', name: 'AVONMORE' },
{ symbol: 'AVROIND.NS', name: 'AVROIND' },
{ symbol: 'AVTNPL.NS', name: 'AVTNPL' },
{ symbol: 'AWFIS.NS', name: 'AWFIS' },
{ symbol: 'AWHCL.NS', name: 'AWHCL' },
{ symbol: 'AWL.NS', name: 'AWL' },
{ symbol: 'AXISBANK.NS', name: 'AXISBANK' },
{ symbol: 'AXISCADES.NS', name: 'AXISCADES' },
{ symbol: 'AXITA.NS', name: 'AXITA' },
{ symbol: 'AYE.NS', name: 'AYE' },
{ symbol: 'AYMSYNTEX.NS', name: 'AYMSYNTEX' },
{ symbol: 'AZAD.NS', name: 'AZAD' },
{ symbol: 'BAFNAPH.NS', name: 'BAFNAPH' },
{ symbol: 'BAGFILMS.NS', name: 'BAGFILMS' },
{ symbol: 'BAIDFIN.NS', name: 'BAIDFIN' },
{ symbol: 'BAJAJ-AUTO.NS', name: 'BAJAJ-AUTO' },
{ symbol: 'BAJAJCON.NS', name: 'BAJAJCON' },
{ symbol: 'BAJAJELEC.NS', name: 'BAJAJELEC' },
{ symbol: 'BAJAJFINSV.NS', name: 'BAJAJFINSV' },
{ symbol: 'BAJAJHCARE.NS', name: 'BAJAJHCARE' },
{ symbol: 'BAJAJHFL.NS', name: 'BAJAJHFL' },
{ symbol: 'BAJAJHIND.NS', name: 'BAJAJHIND' },
{ symbol: 'BAJAJHLDNG.NS', name: 'BAJAJHLDNG' },
{ symbol: 'BAJAJINDEF.NS', name: 'BAJAJINDEF' },
{ symbol: 'BAJAJST.NS', name: 'BAJAJST' },
{ symbol: 'BAJEL.NS', name: 'BAJEL' },
{ symbol: 'BAJFINANCE.NS', name: 'BAJFINANCE' },
{ symbol: 'BALAJEE.NS', name: 'BALAJEE' },
{ symbol: 'BALAJITELE.NS', name: 'BALAJITELE' },
{ symbol: 'BALAMINES.NS', name: 'BALAMINES' },
{ symbol: 'BALAXI.NS', name: 'BALAXI' },
{ symbol: 'BALKRISHNA.NS', name: 'BALKRISHNA' },
{ symbol: 'BALKRISIND.NS', name: 'BALKRISIND' },
{ symbol: 'BALMLAWRIE.NS', name: 'BALMLAWRIE' },
{ symbol: 'BALPHARMA.NS', name: 'BALPHARMA' },
{ symbol: 'BALRAMCHIN.NS', name: 'BALRAMCHIN' },
{ symbol: 'BALUFORGE.NS', name: 'BALUFORGE' },
{ symbol: 'BANARBEADS.NS', name: 'BANARBEADS' },
{ symbol: 'BANARISUG.NS', name: 'BANARISUG' },
{ symbol: 'BANCOINDIA.NS', name: 'BANCOINDIA' },
{ symbol: 'BANDHANBNK.NS', name: 'BANDHANBNK' },
{ symbol: 'BANG.NS', name: 'BANG' },
{ symbol: 'BANKA.NS', name: 'BANKA' },
{ symbol: 'BANKBARODA.NS', name: 'BANKBARODA' },
{ symbol: 'BANKINDIA.NS', name: 'BANKINDIA' },
{ symbol: 'BANSALWIRE.NS', name: 'BANSALWIRE' },
{ symbol: 'BANSWRAS.NS', name: 'BANSWRAS' },
{ symbol: 'BASF.NS', name: 'BASF' },
{ symbol: 'BASML.NS', name: 'BASML' },
{ symbol: 'BATAINDIA.NS', name: 'BATAINDIA' },
{ symbol: 'BATLIBOI.NS', name: 'BATLIBOI' },
{ symbol: 'BAYERCROP.NS', name: 'BAYERCROP' },
{ symbol: 'BBL.NS', name: 'BBL' },
{ symbol: 'BBOX.NS', name: 'BBOX' },
{ symbol: 'BBTC.NS', name: 'BBTC' },
{ symbol: 'BBTCL.NS', name: 'BBTCL' },
{ symbol: 'BCG.NS', name: 'BCG' },
{ symbol: 'BCLIND.NS', name: 'BCLIND' },
{ symbol: 'BCONCEPTS.NS', name: 'BCONCEPTS' },
{ symbol: 'BCPL.NS', name: 'BCPL' },
{ symbol: 'BDL.NS', name: 'BDL' },
{ symbol: 'BEARDSELL.NS', name: 'BEARDSELL' },
{ symbol: 'BECTORFOOD.NS', name: 'BECTORFOOD' },
{ symbol: 'BEDMUTHA.NS', name: 'BEDMUTHA' },
{ symbol: 'BEEKAY.NS', name: 'BEEKAY' },
{ symbol: 'BEL.NS', name: 'BEL' },
{ symbol: 'BELLACASA.NS', name: 'BELLACASA' },
{ symbol: 'BELRISE.NS', name: 'BELRISE' },
{ symbol: 'BEML.NS', name: 'BEML' },
{ symbol: 'BENGALASM.NS', name: 'BENGALASM' },
{ symbol: 'BEPL.NS', name: 'BEPL' },
{ symbol: 'BERGEPAINT.NS', name: 'BERGEPAINT' },
{ symbol: 'BESTAGRO.NS', name: 'BESTAGRO' },
{ symbol: 'BETA.NS', name: 'BETA' },
{ symbol: 'BFINVEST.NS', name: 'BFINVEST' },
{ symbol: 'BFUTILITIE.NS', name: 'BFUTILITIE' },
{ symbol: 'BGRENERGY.NS', name: 'BGRENERGY' },
{ symbol: 'BHAGCHEM.NS', name: 'BHAGCHEM' },
{ symbol: 'BHAGERIA.NS', name: 'BHAGERIA' },
{ symbol: 'BHAGYANGR.NS', name: 'BHAGYANGR' },
{ symbol: 'BHANDARI.NS', name: 'BHANDARI' },
{ symbol: 'BHARATCOAL.NS', name: 'BHARATCOAL' },
{ symbol: 'BHARATFORG.NS', name: 'BHARATFORG' },
{ symbol: 'BHARATGEAR.NS', name: 'BHARATGEAR' },
{ symbol: 'BHARATRAS.NS', name: 'BHARATRAS' },
{ symbol: 'BHARATSE.NS', name: 'BHARATSE' },
{ symbol: 'BHARATWIRE.NS', name: 'BHARATWIRE' },
{ symbol: 'BHARTIARTL.NS', name: 'BHARTIARTL' },
{ symbol: 'BHARTIHEXA.NS', name: 'BHARTIHEXA' },
{ symbol: 'BHEL.NS', name: 'BHEL' },
{ symbol: 'BI.NS', name: 'BI' },
{ symbol: 'BIGBLOC.NS', name: 'BIGBLOC' },
{ symbol: 'BIKAJI.NS', name: 'BIKAJI' },
{ symbol: 'BIL.NS', name: 'BIL' },
{ symbol: 'BILVYAPAR.NS', name: 'BILVYAPAR' },
{ symbol: 'BIMETAL.NS', name: 'BIMETAL' },
{ symbol: 'BIOCON.NS', name: 'BIOCON' },
{ symbol: 'BIOFILCHEM.NS', name: 'BIOFILCHEM' },
{ symbol: 'BIRLACABLE.NS', name: 'BIRLACABLE' },
{ symbol: 'BIRLACORPN.NS', name: 'BIRLACORPN' },
{ symbol: 'BIRLAMONEY.NS', name: 'BIRLAMONEY' },
{ symbol: 'BIRLANU.NS', name: 'BIRLANU' },
{ symbol: 'BIRLAPREC.NS', name: 'BIRLAPREC' },
{ symbol: 'BLACKBUCK.NS', name: 'BLACKBUCK' },
{ symbol: 'BLACKROSE.NS', name: 'BLACKROSE' },
{ symbol: 'BLAL.NS', name: 'BLAL' },
{ symbol: 'BLBLIMITED.NS', name: 'BLBLIMITED' },
{ symbol: 'BLIL.NS', name: 'BLIL' },
{ symbol: 'BLISSGVS.NS', name: 'BLISSGVS' },
{ symbol: 'BLKASHYAP.NS', name: 'BLKASHYAP' },
{ symbol: 'BLS.NS', name: 'BLS' },
{ symbol: 'BLSE.NS', name: 'BLSE' },
{ symbol: 'BLUECHIP.NS', name: 'BLUECHIP' },
{ symbol: 'BLUECOAST.NS', name: 'BLUECOAST' },
{ symbol: 'BLUEDART.NS', name: 'BLUEDART' },
{ symbol: 'BLUEJET.NS', name: 'BLUEJET' },
{ symbol: 'BLUESTARCO.NS', name: 'BLUESTARCO' },
{ symbol: 'BLUESTONE.NS', name: 'BLUESTONE' },
{ symbol: 'BLUSPRING.NS', name: 'BLUSPRING' },
{ symbol: 'BMWVENTLTD.NS', name: 'BMWVENTLTD' },
{ symbol: 'BNAGROCHEM.NS', name: 'BNAGROCHEM' },
{ symbol: 'BNALTD.NS', name: 'BNALTD' },
{ symbol: 'BODALCHEM.NS', name: 'BODALCHEM' },
{ symbol: 'BOHRAIND.NS', name: 'BOHRAIND' },
{ symbol: 'BOMDYEING.NS', name: 'BOMDYEING' },
{ symbol: 'BONLON.NS', name: 'BONLON' },
{ symbol: 'BORANA.NS', name: 'BORANA' },
{ symbol: 'BOROLTD.NS', name: 'BOROLTD' },
{ symbol: 'BORORENEW.NS', name: 'BORORENEW' },
{ symbol: 'BOROSCI.NS', name: 'BOROSCI' },
{ symbol: 'BOSCH-HCIL.NS', name: 'BOSCH-HCIL' },
{ symbol: 'BOSCHLTD.NS', name: 'BOSCHLTD' },
{ symbol: 'BPCL.NS', name: 'BPCL' },
{ symbol: 'BPL.NS', name: 'BPL' },
{ symbol: 'BRIGADE.NS', name: 'BRIGADE' },
{ symbol: 'BRIGHOTEL.NS', name: 'BRIGHOTEL' },
{ symbol: 'BRITANNIA.NS', name: 'BRITANNIA' },
{ symbol: 'BRNL.NS', name: 'BRNL' },
{ symbol: 'BROOKS.NS', name: 'BROOKS' },
{ symbol: 'BSE.NS', name: 'BSE' },
{ symbol: 'BSHSL.NS', name: 'BSHSL' },
{ symbol: 'BSL.NS', name: 'BSL' },
{ symbol: 'BSOFT.NS', name: 'BSOFT' },
{ symbol: 'BTML.NS', name: 'BTML' },
{ symbol: 'BTTL.NS', name: 'BTTL' },
{ symbol: 'BUILDPRO.NS', name: 'BUILDPRO' },
{ symbol: 'BUTTERFLY.NS', name: 'BUTTERFLY' },
{ symbol: 'BVCL.NS', name: 'BVCL' },
{ symbol: 'BYKE.NS', name: 'BYKE' },
{ symbol: 'CALSOFT.NS', name: 'CALSOFT' },
{ symbol: 'CAMLINFINE.NS', name: 'CAMLINFINE' },
{ symbol: 'CAMPUS.NS', name: 'CAMPUS' },
{ symbol: 'CAMS.NS', name: 'CAMS' },
{ symbol: 'CANBK.NS', name: 'CANBK' },
{ symbol: 'CANFINHOME.NS', name: 'CANFINHOME' },
{ symbol: 'CANHLIFE.NS', name: 'CANHLIFE' },
{ symbol: 'CANTABIL.NS', name: 'CANTABIL' },
{ symbol: 'CAPACITE.NS', name: 'CAPACITE' },
{ symbol: 'CAPILLARY.NS', name: 'CAPILLARY' },
{ symbol: 'CAPITALSFB.NS', name: 'CAPITALSFB' },
{ symbol: 'CAPLIPOINT.NS', name: 'CAPLIPOINT' },
{ symbol: 'CAPTRUST.NS', name: 'CAPTRUST' },
{ symbol: 'CARBORUNIV.NS', name: 'CARBORUNIV' },
{ symbol: 'CARERATING.NS', name: 'CARERATING' },
{ symbol: 'CARRARO.NS', name: 'CARRARO' },
{ symbol: 'CARTRADE.NS', name: 'CARTRADE' },
{ symbol: 'CARYSIL.NS', name: 'CARYSIL' },
{ symbol: 'CASTROLIND.NS', name: 'CASTROLIND' },
{ symbol: 'CCAVENUE.NS', name: 'CCAVENUE' },
{ symbol: 'CCCL.NS', name: 'CCCL' },
{ symbol: 'CCHHL.NS', name: 'CCHHL' },
{ symbol: 'CCL.NS', name: 'CCL' },
{ symbol: 'CDSL.NS', name: 'CDSL' },
{ symbol: 'CEATLTD.NS', name: 'CEATLTD' },
{ symbol: 'CEIGALL.NS', name: 'CEIGALL' },
{ symbol: 'CEINSYS.NS', name: 'CEINSYS' },
{ symbol: 'CELEBRITY.NS', name: 'CELEBRITY' },
{ symbol: 'CELLO.NS', name: 'CELLO' },
{ symbol: 'CEMPRO.NS', name: 'CEMPRO' },
{ symbol: 'CENTENKA.NS', name: 'CENTENKA' },
{ symbol: 'CENTEXT.NS', name: 'CENTEXT' },
{ symbol: 'CENTRALBK.NS', name: 'CENTRALBK' },
{ symbol: 'CENTRUM.NS', name: 'CENTRUM' },
{ symbol: 'CENTUM.NS', name: 'CENTUM' },
{ symbol: 'CENTURYPLY.NS', name: 'CENTURYPLY' },
{ symbol: 'CERA.NS', name: 'CERA' },
{ symbol: 'CEREBRAINT.NS', name: 'CEREBRAINT' },
{ symbol: 'CESC.NS', name: 'CESC' },
{ symbol: 'CEWATER.NS', name: 'CEWATER' },
{ symbol: 'CGCL.NS', name: 'CGCL' },
{ symbol: 'CGPOWER.NS', name: 'CGPOWER' },
{ symbol: 'CHALET.NS', name: 'CHALET' },
{ symbol: 'CHAMBLFERT.NS', name: 'CHAMBLFERT' },
{ symbol: 'CHEMBOND.NS', name: 'CHEMBOND' },
{ symbol: 'CHEMBONDCH.NS', name: 'CHEMBONDCH' },
{ symbol: 'CHEMCON.NS', name: 'CHEMCON' },
{ symbol: 'CHEMFAB.NS', name: 'CHEMFAB' },
{ symbol: 'CHEMPLASTS.NS', name: 'CHEMPLASTS' },
{ symbol: 'CHENNPETRO.NS', name: 'CHENNPETRO' },
{ symbol: 'CHEVIOT.NS', name: 'CHEVIOT' },
{ symbol: 'CHOICEIN.NS', name: 'CHOICEIN' },
{ symbol: 'CHOLAFIN.NS', name: 'CHOLAFIN' },
{ symbol: 'CHOLAHLDNG.NS', name: 'CHOLAHLDNG' },
{ symbol: 'CIEINDIA.NS', name: 'CIEINDIA' },
{ symbol: 'CIFL.NS', name: 'CIFL' },
{ symbol: 'CINELINE.NS', name: 'CINELINE' },
{ symbol: 'CINEVISTA.NS', name: 'CINEVISTA' },
{ symbol: 'CIPLA.NS', name: 'CIPLA' },
{ symbol: 'CLEAN.NS', name: 'CLEAN' },
{ symbol: 'CLEANMAX.NS', name: 'CLEANMAX' },
{ symbol: 'CLEDUCATE.NS', name: 'CLEDUCATE' },
{ symbol: 'CLSEL.NS', name: 'CLSEL' },
{ symbol: 'CMPDI.NS', name: 'CMPDI' },
{ symbol: 'CMRGREEN.NS', name: 'CMRGREEN' },
{ symbol: 'CMSINFO.NS', name: 'CMSINFO' },
{ symbol: 'CNL.NS', name: 'CNL' },
{ symbol: 'COALINDIA.NS', name: 'COALINDIA' },
{ symbol: 'COASTCORP.NS', name: 'COASTCORP' },
{ symbol: 'COCHINSHIP.NS', name: 'COCHINSHIP' },
{ symbol: 'COCKERILL.NS', name: 'COCKERILL' },
{ symbol: 'COFFEEDAY.NS', name: 'COFFEEDAY' },
{ symbol: 'COFORGE.NS', name: 'COFORGE' },
{ symbol: 'COHANCE.NS', name: 'COHANCE' },
{ symbol: 'COLPAL.NS', name: 'COLPAL' },
{ symbol: 'COMFINTE.NS', name: 'COMFINTE' },
{ symbol: 'COMPINFO.NS', name: 'COMPINFO' },
{ symbol: 'COMPUSOFT.NS', name: 'COMPUSOFT' },
{ symbol: 'COMSYN.NS', name: 'COMSYN' },
{ symbol: 'CONCOR.NS', name: 'CONCOR' },
{ symbol: 'CONCORDBIO.NS', name: 'CONCORDBIO' },
{ symbol: 'CONFIPET.NS', name: 'CONFIPET' },
{ symbol: 'CONSOFINVT.NS', name: 'CONSOFINVT' },
{ symbol: 'CONTROLPR.NS', name: 'CONTROLPR' },
{ symbol: 'CORALFINAC.NS', name: 'CORALFINAC' },
{ symbol: 'CORDELIA.NS', name: 'CORDELIA' },
{ symbol: 'CORDSCABLE.NS', name: 'CORDSCABLE' },
{ symbol: 'COROMANDEL.NS', name: 'COROMANDEL' },
{ symbol: 'CORONA.NS', name: 'CORONA' },
{ symbol: 'COSMOFIRST.NS', name: 'COSMOFIRST' },
{ symbol: 'COUNCODOS.NS', name: 'COUNCODOS' },
{ symbol: 'CPCAP.NS', name: 'CPCAP' },
{ symbol: 'CPEDU.NS', name: 'CPEDU' },
{ symbol: 'CPL.NS', name: 'CPL' },
{ symbol: 'CPPLUS.NS', name: 'CPPLUS' },
{ symbol: 'CRAFTSMAN.NS', name: 'CRAFTSMAN' },
{ symbol: 'CRAMC.NS', name: 'CRAMC' },
{ symbol: 'CREATIVEYE.NS', name: 'CREATIVEYE' },
{ symbol: 'CREDITACC.NS', name: 'CREDITACC' },
{ symbol: 'CREST.NS', name: 'CREST' },
{ symbol: 'CRISIL.NS', name: 'CRISIL' },
{ symbol: 'CRIZAC.NS', name: 'CRIZAC' },
{ symbol: 'CROMPTON.NS', name: 'CROMPTON' },
{ symbol: 'CROWN.NS', name: 'CROWN' },
{ symbol: 'CSBBANK.NS', name: 'CSBBANK' },
{ symbol: 'CSLFINANCE.NS', name: 'CSLFINANCE' },
{ symbol: 'CSM.NS', name: 'CSM' },
{ symbol: 'CTE.NS', name: 'CTE' },
{ symbol: 'CUB.NS', name: 'CUB' },
{ symbol: 'CUBEXTUB.NS', name: 'CUBEXTUB' },
{ symbol: 'CUMMINSIND.NS', name: 'CUMMINSIND' },
{ symbol: 'CUPID.NS', name: 'CUPID' },
{ symbol: 'CURAA.NS', name: 'CURAA' },
{ symbol: 'CYBERMEDIA.NS', name: 'CYBERMEDIA' },
{ symbol: 'CYBERTECH.NS', name: 'CYBERTECH' },
{ symbol: 'CYIENT.NS', name: 'CYIENT' },
{ symbol: 'CYIENTDLM.NS', name: 'CYIENTDLM' },
{ symbol: 'DABUR.NS', name: 'DABUR' },
{ symbol: 'DAICHI.NS', name: 'DAICHI' },
{ symbol: 'DALBHARAT.NS', name: 'DALBHARAT' },
{ symbol: 'DALMIASUG.NS', name: 'DALMIASUG' },
{ symbol: 'DAMCAPITAL.NS', name: 'DAMCAPITAL' },
{ symbol: 'DAMODARIND.NS', name: 'DAMODARIND' },
{ symbol: 'DANGEE.NS', name: 'DANGEE' },
{ symbol: 'DATAMATICS.NS', name: 'DATAMATICS' },
{ symbol: 'DATAPATTNS.NS', name: 'DATAPATTNS' },
{ symbol: 'DAVANGERE.NS', name: 'DAVANGERE' },
{ symbol: 'DBCORP.NS', name: 'DBCORP' },
{ symbol: 'DBEIL.NS', name: 'DBEIL' },
{ symbol: 'DBL.NS', name: 'DBL' },
{ symbol: 'DBOL.NS', name: 'DBOL' },
{ symbol: 'DBREALTY.NS', name: 'DBREALTY' },
{ symbol: 'DBSTOCKBRO.NS', name: 'DBSTOCKBRO' },
{ symbol: 'DCAL.NS', name: 'DCAL' },
{ symbol: 'DCBBANK.NS', name: 'DCBBANK' },
{ symbol: 'DCI.NS', name: 'DCI' },
{ symbol: 'DCM.NS', name: 'DCM' },
{ symbol: 'DCMFINSERV.NS', name: 'DCMFINSERV' },
{ symbol: 'DCMNVL.NS', name: 'DCMNVL' },
{ symbol: 'DCMSHRIRAM.NS', name: 'DCMSHRIRAM' },
{ symbol: 'DCMSIL.NS', name: 'DCMSIL' },
{ symbol: 'DCMSRIND.NS', name: 'DCMSRIND' },
{ symbol: 'DCW.NS', name: 'DCW' },
{ symbol: 'DCXINDIA.NS', name: 'DCXINDIA' },
{ symbol: 'DDEVPLSTIK.NS', name: 'DDEVPLSTIK' },
{ symbol: 'DECCANCE.NS', name: 'DECCANCE' },
{ symbol: 'DECNGOLD.NS', name: 'DECNGOLD' },
{ symbol: 'DEEDEV.NS', name: 'DEEDEV' },
{ symbol: 'DEEPAKFERT.NS', name: 'DEEPAKFERT' },
{ symbol: 'DEEPAKNTR.NS', name: 'DEEPAKNTR' },
{ symbol: 'DEEPINDS.NS', name: 'DEEPINDS' },
{ symbol: 'DELHIVERY.NS', name: 'DELHIVERY' },
{ symbol: 'DELPHIFX.NS', name: 'DELPHIFX' },
{ symbol: 'DELTACORP.NS', name: 'DELTACORP' },
{ symbol: 'DELTAMAGNT.NS', name: 'DELTAMAGNT' },
{ symbol: 'DEN.NS', name: 'DEN' },
{ symbol: 'DENORA.NS', name: 'DENORA' },
{ symbol: 'DENTA.NS', name: 'DENTA' },
{ symbol: 'DEVIT.NS', name: 'DEVIT' },
{ symbol: 'DEVX.NS', name: 'DEVX' },
{ symbol: 'DEVYANI.NS', name: 'DEVYANI' },
{ symbol: 'DGCONTENT.NS', name: 'DGCONTENT' },
{ symbol: 'DHAMPURSUG.NS', name: 'DHAMPURSUG' },
{ symbol: 'DHANBANK.NS', name: 'DHANBANK' },
{ symbol: 'DHANUKA.NS', name: 'DHANUKA' },
{ symbol: 'DHARAN.NS', name: 'DHARAN' },
{ symbol: 'DHARMAJ.NS', name: 'DHARMAJ' },
{ symbol: 'DHRUV.NS', name: 'DHRUV' },
{ symbol: 'DHUNINV.NS', name: 'DHUNINV' },
{ symbol: 'DIACABS.NS', name: 'DIACABS' },
{ symbol: 'DIAMINESQ.NS', name: 'DIAMINESQ' },
{ symbol: 'DIAMONDYD.NS', name: 'DIAMONDYD' },
{ symbol: 'DICIND.NS', name: 'DICIND' },
{ symbol: 'DIFFNKG.NS', name: 'DIFFNKG' },
{ symbol: 'DIGIDRIVE.NS', name: 'DIGIDRIVE' },
{ symbol: 'DIGISPICE.NS', name: 'DIGISPICE' },
{ symbol: 'DIGITIDE.NS', name: 'DIGITIDE' },
{ symbol: 'DIGJAMLMTD.NS', name: 'DIGJAMLMTD' },
{ symbol: 'DISAQ.NS', name: 'DISAQ' },
{ symbol: 'DISHTV.NS', name: 'DISHTV' },
{ symbol: 'DIVGIITTS.NS', name: 'DIVGIITTS' },
{ symbol: 'DIVISLAB.NS', name: 'DIVISLAB' },
{ symbol: 'DIXON.NS', name: 'DIXON' },
{ symbol: 'DJML.NS', name: 'DJML' },
{ symbol: 'DLF.NS', name: 'DLF' },
{ symbol: 'DLINKINDIA.NS', name: 'DLINKINDIA' },
{ symbol: 'DMART.NS', name: 'DMART' },
{ symbol: 'DMCC.NS', name: 'DMCC' },
{ symbol: 'DNAMEDIA.NS', name: 'DNAMEDIA' },
{ symbol: 'DODLA.NS', name: 'DODLA' },
{ symbol: 'DOLATALGO.NS', name: 'DOLATALGO' },
{ symbol: 'DOLLAR.NS', name: 'DOLLAR' },
{ symbol: 'DOLPHIN.NS', name: 'DOLPHIN' },
{ symbol: 'DOMS.NS', name: 'DOMS' },
{ symbol: 'DONEAR.NS', name: 'DONEAR' },
{ symbol: 'DPABHUSHAN.NS', name: 'DPABHUSHAN' },
{ symbol: 'DPSCLTD.NS', name: 'DPSCLTD' },
{ symbol: 'DPWIRES.NS', name: 'DPWIRES' },
{ symbol: 'DRAGARWQ.NS', name: 'DRAGARWQ' },
{ symbol: 'DRCSYSTEMS.NS', name: 'DRCSYSTEMS' },
{ symbol: 'DREAMFOLKS.NS', name: 'DREAMFOLKS' },
{ symbol: 'DREDGECORP.NS', name: 'DREDGECORP' },
{ symbol: 'DRREDDY.NS', name: 'DRREDDY' },
{ symbol: 'DSFCL.NS', name: 'DSFCL' },
{ symbol: 'DSSL.NS', name: 'DSSL' },
{ symbol: 'DTIL.NS', name: 'DTIL' },
{ symbol: 'DUCON.NS', name: 'DUCON' },
{ symbol: 'DVL.NS', name: 'DVL' },
{ symbol: 'DWARKESH.NS', name: 'DWARKESH' },
{ symbol: 'DYCL.NS', name: 'DYCL' },
{ symbol: 'DYNAMATECH.NS', name: 'DYNAMATECH' },
{ symbol: 'DYNPRO.NS', name: 'DYNPRO' },
{ symbol: 'E2E.NS', name: 'E2E' },
{ symbol: 'EASEMYTRIP.NS', name: 'EASEMYTRIP' },
{ symbol: 'EASTSILK.NS', name: 'EASTSILK' },
{ symbol: 'EBGNG.NS', name: 'EBGNG' },
{ symbol: 'ECLERX.NS', name: 'ECLERX' },
{ symbol: 'ECOSMOBLTY.NS', name: 'ECOSMOBLTY' },
{ symbol: 'EDELWEISS.NS', name: 'EDELWEISS' },
{ symbol: 'EFCIL.NS', name: 'EFCIL' },
{ symbol: 'EICHERMOT.NS', name: 'EICHERMOT' },
{ symbol: 'EIDPARRY.NS', name: 'EIDPARRY' },
{ symbol: 'EIEL.NS', name: 'EIEL' },
{ symbol: 'EIFFL.NS', name: 'EIFFL' },
{ symbol: 'EIHAHOTELS.NS', name: 'EIHAHOTELS' },
{ symbol: 'EIHOTEL.NS', name: 'EIHOTEL' },
{ symbol: 'EIMCOELECO.NS', name: 'EIMCOELECO' },
{ symbol: 'EKC.NS', name: 'EKC' },
{ symbol: 'ELANTAS.NS', name: 'ELANTAS' },
{ symbol: 'ELCIDIN.NS', name: 'ELCIDIN' },
{ symbol: 'ELDEHSG.NS', name: 'ELDEHSG' },
{ symbol: 'ELECON.NS', name: 'ELECON' },
{ symbol: 'ELECTCAST.NS', name: 'ELECTCAST' },
{ symbol: 'ELECTHERM.NS', name: 'ELECTHERM' },
{ symbol: 'ELGIEQUIP.NS', name: 'ELGIEQUIP' },
{ symbol: 'ELGIRUBCO.NS', name: 'ELGIRUBCO' },
{ symbol: 'ELIN.NS', name: 'ELIN' },
{ symbol: 'ELITECON.NS', name: 'ELITECON' },
{ symbol: 'ELLEN.NS', name: 'ELLEN' },
{ symbol: 'ELPROINTL.NS', name: 'ELPROINTL' },
{ symbol: 'EMAMILTD.NS', name: 'EMAMILTD' },
{ symbol: 'EMAMIPAP.NS', name: 'EMAMIPAP' },
{ symbol: 'EMAMIREAL.NS', name: 'EMAMIREAL' },
{ symbol: 'EMBDL.NS', name: 'EMBDL' },
{ symbol: 'EMCURE.NS', name: 'EMCURE' },
{ symbol: 'EMIL.NS', name: 'EMIL' },
{ symbol: 'EMKAY.NS', name: 'EMKAY' },
{ symbol: 'EMMBI.NS', name: 'EMMBI' },
{ symbol: 'EMMVEE.NS', name: 'EMMVEE' },
{ symbol: 'EMPOWER.NS', name: 'EMPOWER' },
{ symbol: 'EMSLIMITED.NS', name: 'EMSLIMITED' },
{ symbol: 'EMUDHRA.NS', name: 'EMUDHRA' },
{ symbol: 'ENDURANCE.NS', name: 'ENDURANCE' },
{ symbol: 'ENERGYDEV.NS', name: 'ENERGYDEV' },
{ symbol: 'ENGINERSIN.NS', name: 'ENGINERSIN' },
{ symbol: 'ENIL.NS', name: 'ENIL' },
{ symbol: 'ENRIN.NS', name: 'ENRIN' },
{ symbol: 'ENTERO.NS', name: 'ENTERO' },
{ symbol: 'EPACK.NS', name: 'EPACK' },
{ symbol: 'EPACKPEB.NS', name: 'EPACKPEB' },
{ symbol: 'EPIGRAL.NS', name: 'EPIGRAL' },
{ symbol: 'EPL.NS', name: 'EPL' },
{ symbol: 'EQUIPPP.NS', name: 'EQUIPPP' },
{ symbol: 'EQUITASBNK.NS', name: 'EQUITASBNK' },
{ symbol: 'ERIS.NS', name: 'ERIS' },
{ symbol: 'ESABINDIA.NS', name: 'ESABINDIA' },
{ symbol: 'ESAFSFB.NS', name: 'ESAFSFB' },
{ symbol: 'ESCORTS.NS', name: 'ESCORTS' },
{ symbol: 'ESSARSHPNG.NS', name: 'ESSARSHPNG' },
{ symbol: 'ESSENTIA.NS', name: 'ESSENTIA' },
{ symbol: 'ESTER.NS', name: 'ESTER' },
{ symbol: 'ETERNAL.NS', name: 'ETERNAL' },
{ symbol: 'ETHOSLTD.NS', name: 'ETHOSLTD' },
{ symbol: 'EUREKAFORB.NS', name: 'EUREKAFORB' },
{ symbol: 'EUROBOND.NS', name: 'EUROBOND' },
{ symbol: 'EUROPRATIK.NS', name: 'EUROPRATIK' },
{ symbol: 'EUROTEXIND.NS', name: 'EUROTEXIND' },
{ symbol: 'EVEREADY.NS', name: 'EVEREADY' },
{ symbol: 'EVERESTIND.NS', name: 'EVERESTIND' },
{ symbol: 'EXCELINDUS.NS', name: 'EXCELINDUS' },
{ symbol: 'EXCELSOFT.NS', name: 'EXCELSOFT' },
{ symbol: 'EXICOM.NS', name: 'EXICOM' },
{ symbol: 'EXIDEIND.NS', name: 'EXIDEIND' },
{ symbol: 'EXPLEOSOL.NS', name: 'EXPLEOSOL' },
{ symbol: 'EXXARO.NS', name: 'EXXARO' },
{ symbol: 'FABTECH.NS', name: 'FABTECH' },
{ symbol: 'FACT.NS', name: 'FACT' },
{ symbol: 'FAIRCHEMOR.NS', name: 'FAIRCHEMOR' },
{ symbol: 'FAZE3Q.NS', name: 'FAZE3Q' },
{ symbol: 'FCL.NS', name: 'FCL' },
{ symbol: 'FCSSOFT.NS', name: 'FCSSOFT' },
{ symbol: 'FDC.NS', name: 'FDC' },
{ symbol: 'FEDDERSHOL.NS', name: 'FEDDERSHOL' },
{ symbol: 'FEDERALBNK.NS', name: 'FEDERALBNK' },
{ symbol: 'FEDFINA.NS', name: 'FEDFINA' },
{ symbol: 'FEL.NS', name: 'FEL' },
{ symbol: 'FELDVR.NS', name: 'FELDVR' },
{ symbol: 'FERMENTA.NS', name: 'FERMENTA' },
{ symbol: 'FIBERWEB.NS', name: 'FIBERWEB' },
{ symbol: 'FIEMIND.NS', name: 'FIEMIND' },
{ symbol: 'FILATEX.NS', name: 'FILATEX' },
{ symbol: 'FILATFASH.NS', name: 'FILATFASH' },
{ symbol: 'FINCABLES.NS', name: 'FINCABLES' },
{ symbol: 'FINEORG.NS', name: 'FINEORG' },
{ symbol: 'FINKURVE.NS', name: 'FINKURVE' },
{ symbol: 'FINOPB.NS', name: 'FINOPB' },
{ symbol: 'FINPIPE.NS', name: 'FINPIPE' },
{ symbol: 'FIRSTCRY.NS', name: 'FIRSTCRY' },
{ symbol: 'FISCHER.NS', name: 'FISCHER' },
{ symbol: 'FIVESTAR.NS', name: 'FIVESTAR' },
{ symbol: 'FLAIR.NS', name: 'FLAIR' },
{ symbol: 'FLEXITUFF.NS', name: 'FLEXITUFF' },
{ symbol: 'FLFL.NS', name: 'FLFL' },
{ symbol: 'FLUOROCHEM.NS', name: 'FLUOROCHEM' },
{ symbol: 'FMGOETZE.NS', name: 'FMGOETZE' },
{ symbol: 'FMNL.NS', name: 'FMNL' },
{ symbol: 'FOCUS.NS', name: 'FOCUS' },
{ symbol: 'FOODSIN.NS', name: 'FOODSIN' },
{ symbol: 'FORCEMOT.NS', name: 'FORCEMOT' },
{ symbol: 'FORTIS.NS', name: 'FORTIS' },
{ symbol: 'FOSECOIND.NS', name: 'FOSECOIND' },
{ symbol: 'FRACTAL.NS', name: 'FRACTAL' },
{ symbol: 'FRONTSP.NS', name: 'FRONTSP' },
{ symbol: 'FSL.NS', name: 'FSL' },
{ symbol: 'FUSION.NS', name: 'FUSION' },
{ symbol: 'GABRIEL.NS', name: 'GABRIEL' },
{ symbol: 'GAEL.NS', name: 'GAEL' },
{ symbol: 'GAIL.NS', name: 'GAIL' },
{ symbol: 'GALAPREC.NS', name: 'GALAPREC' },
{ symbol: 'GALAXYSURF.NS', name: 'GALAXYSURF' },
{ symbol: 'GALLANTT.NS', name: 'GALLANTT' },
{ symbol: 'GANDHAR.NS', name: 'GANDHAR' },
{ symbol: 'GANDHITUBE.NS', name: 'GANDHITUBE' },
{ symbol: 'GANECOS.NS', name: 'GANECOS' },
{ symbol: 'GANESHBE.NS', name: 'GANESHBE' },
{ symbol: 'GANESHCP.NS', name: 'GANESHCP' },
{ symbol: 'GANESHHOU.NS', name: 'GANESHHOU' },
{ symbol: 'GANGAFORGE.NS', name: 'GANGAFORGE' },
{ symbol: 'GANGESSECU.NS', name: 'GANGESSECU' },
{ symbol: 'GARFIBRES.NS', name: 'GARFIBRES' },
{ symbol: 'GARUDA.NS', name: 'GARUDA' },
{ symbol: 'GATECH.NS', name: 'GATECH' },
{ symbol: 'GATECHDVR.NS', name: 'GATECHDVR' },
{ symbol: 'GATEWAY.NS', name: 'GATEWAY' },
{ symbol: 'GAUDIUMIVF.NS', name: 'GAUDIUMIVF' },
{ symbol: 'GAYAHWS.NS', name: 'GAYAHWS' },
{ symbol: 'GAYAPROJ.NS', name: 'GAYAPROJ' },
{ symbol: 'GCSL.NS', name: 'GCSL' },
{ symbol: 'GEECEE.NS', name: 'GEECEE' },
{ symbol: 'GEEKAYWIRE.NS', name: 'GEEKAYWIRE' },
{ symbol: 'GEMAROMA.NS', name: 'GEMAROMA' },
{ symbol: 'GENCON.NS', name: 'GENCON' },
{ symbol: 'GENESYS.NS', name: 'GENESYS' },
{ symbol: 'GENUSPAPER.NS', name: 'GENUSPAPER' },
{ symbol: 'GENUSPOWER.NS', name: 'GENUSPOWER' },
{ symbol: 'GEOJITFSL.NS', name: 'GEOJITFSL' },
{ symbol: 'GESHIP.NS', name: 'GESHIP' },
{ symbol: 'GFLLIMITED.NS', name: 'GFLLIMITED' },
{ symbol: 'GHCL.NS', name: 'GHCL' },
{ symbol: 'GHCLTEXTIL.NS', name: 'GHCLTEXTIL' },
{ symbol: 'GICHSGFIN.NS', name: 'GICHSGFIN' },
{ symbol: 'GICL.NS', name: 'GICL' },
{ symbol: 'GICRE.NS', name: 'GICRE' },
{ symbol: 'GILLANDERS.NS', name: 'GILLANDERS' },
{ symbol: 'GILLETTE.NS', name: 'GILLETTE' },
{ symbol: 'GINNIFILA.NS', name: 'GINNIFILA' },
{ symbol: 'GIPCL.NS', name: 'GIPCL' },
{ symbol: 'GKENERGY.NS', name: 'GKENERGY' },
{ symbol: 'GKSL.NS', name: 'GKSL' },
{ symbol: 'GKWLIMITED.NS', name: 'GKWLIMITED' },
{ symbol: 'GLAND.NS', name: 'GLAND' },
{ symbol: 'GLAXO.NS', name: 'GLAXO' },
{ symbol: 'GLENMARK.NS', name: 'GLENMARK' },
{ symbol: 'GLFL.NS', name: 'GLFL' },
{ symbol: 'GLOBAL.NS', name: 'GLOBAL' },
{ symbol: 'GLOBALE.NS', name: 'GLOBALE' },
{ symbol: 'GLOBALVECT.NS', name: 'GLOBALVECT' },
{ symbol: 'GLOBE.NS', name: 'GLOBE' },
{ symbol: 'GLOBECIVIL.NS', name: 'GLOBECIVIL' },
{ symbol: 'GLOBUSSPR.NS', name: 'GLOBUSSPR' },
{ symbol: 'GLOSTERLTD.NS', name: 'GLOSTERLTD' },
{ symbol: 'GLOTTIS.NS', name: 'GLOTTIS' },
{ symbol: 'GMBREW.NS', name: 'GMBREW' },
{ symbol: 'GMDCLTD.NS', name: 'GMDCLTD' },
{ symbol: 'GMMPFAUDLR.NS', name: 'GMMPFAUDLR' },
{ symbol: 'GMRAIRPORT.NS', name: 'GMRAIRPORT' },
{ symbol: 'GMRP&UI.NS', name: 'GMRP&UI' },
{ symbol: 'GNA.NS', name: 'GNA' },
{ symbol: 'GNFC.NS', name: 'GNFC' },
{ symbol: 'GNRL.NS', name: 'GNRL' },
{ symbol: 'GOACARBON.NS', name: 'GOACARBON' },
{ symbol: 'GOCLCORP.NS', name: 'GOCLCORP' },
{ symbol: 'GOCOLORS.NS', name: 'GOCOLORS' },
{ symbol: 'GODAVARIB.NS', name: 'GODAVARIB' },
{ symbol: 'GODFRYPHLP.NS', name: 'GODFRYPHLP' },
{ symbol: 'GODIGIT.NS', name: 'GODIGIT' },
{ symbol: 'GODREJAGRO.NS', name: 'GODREJAGRO' },
{ symbol: 'GODREJCP.NS', name: 'GODREJCP' },
{ symbol: 'GODREJIND.NS', name: 'GODREJIND' },
{ symbol: 'GODREJPROP.NS', name: 'GODREJPROP' },
{ symbol: 'GOKEX.NS', name: 'GOKEX' },
{ symbol: 'GOKUL.NS', name: 'GOKUL' },
{ symbol: 'GOKULAGRO.NS', name: 'GOKULAGRO' },
{ symbol: 'GOLDENTOBC.NS', name: 'GOLDENTOBC' },
{ symbol: 'GOLDIAM.NS', name: 'GOLDIAM' },
{ symbol: 'GOLDTECH.NS', name: 'GOLDTECH' },
{ symbol: 'GOODLUCK.NS', name: 'GOODLUCK' },
{ symbol: 'GOODYEAR.NS', name: 'GOODYEAR' },
{ symbol: 'GOPAL.NS', name: 'GOPAL' },
{ symbol: 'GOYALALUM.NS', name: 'GOYALALUM' },
{ symbol: 'GPIL.NS', name: 'GPIL' },
{ symbol: 'GPPL.NS', name: 'GPPL' },
{ symbol: 'GPTHEALTH.NS', name: 'GPTHEALTH' },
{ symbol: 'GPTINFRA.NS', name: 'GPTINFRA' },
{ symbol: 'GRADIENTE.NS', name: 'GRADIENTE' },
{ symbol: 'GRANDOAK.NS', name: 'GRANDOAK' },
{ symbol: 'GRANULES.NS', name: 'GRANULES' },
{ symbol: 'GRAPHITE.NS', name: 'GRAPHITE' },
{ symbol: 'GRASIM.NS', name: 'GRASIM' },
{ symbol: 'GRAUWEIL.NS', name: 'GRAUWEIL' },
{ symbol: 'GRAVISSHO.NS', name: 'GRAVISSHO' },
{ symbol: 'GRAVITA.NS', name: 'GRAVITA' },
{ symbol: 'GREAVESCOT.NS', name: 'GREAVESCOT' },
{ symbol: 'GREENLAM.NS', name: 'GREENLAM' },
{ symbol: 'GREENPANEL.NS', name: 'GREENPANEL' },
{ symbol: 'GREENPLY.NS', name: 'GREENPLY' },
{ symbol: 'GREENPOWER.NS', name: 'GREENPOWER' },
{ symbol: 'GRINDWELL.NS', name: 'GRINDWELL' },
{ symbol: 'GRINFRA.NS', name: 'GRINFRA' },
{ symbol: 'GRMOVER.NS', name: 'GRMOVER' },
{ symbol: 'GROBTEA.NS', name: 'GROBTEA' },
{ symbol: 'GROWW.NS', name: 'GROWW' },
{ symbol: 'GRPLTD.NS', name: 'GRPLTD' },
{ symbol: 'GRSE.NS', name: 'GRSE' },
{ symbol: 'GRWRHITECH.NS', name: 'GRWRHITECH' },
{ symbol: 'GSFC.NS', name: 'GSFC' },
{ symbol: 'GSLSU.NS', name: 'GSLSU' },
{ symbol: 'GSPCROP.NS', name: 'GSPCROP' },
{ symbol: 'GSS.NS', name: 'GSS' },
{ symbol: 'GTECJAINX.NS', name: 'GTECJAINX' },
{ symbol: 'GTL.NS', name: 'GTL' },
{ symbol: 'GTLINFRA.NS', name: 'GTLINFRA' },
{ symbol: 'GTPL.NS', name: 'GTPL' },
{ symbol: 'GUFICBIO.NS', name: 'GUFICBIO' },
{ symbol: 'GUJALKALI.NS', name: 'GUJALKALI' },
{ symbol: 'GUJAPOLLO.NS', name: 'GUJAPOLLO' },
{ symbol: 'GUJENERGY.NS', name: 'GUJENERGY' },
{ symbol: 'GUJRAFFIA.NS', name: 'GUJRAFFIA' },
{ symbol: 'GUJTHEM.NS', name: 'GUJTHEM' },
{ symbol: 'GULFOILLUB.NS', name: 'GULFOILLUB' },
{ symbol: 'GULFPETRO.NS', name: 'GULFPETRO' },
{ symbol: 'GULPOLY.NS', name: 'GULPOLY' },
{ symbol: 'GVKPIL.NS', name: 'GVKPIL' },
{ symbol: 'GVPIL.NS', name: 'GVPIL' },
{ symbol: 'GVPTECH.NS', name: 'GVPTECH' },
{ symbol: 'GVT&D.NS', name: 'GVT&D' },
{ symbol: 'GYFTR.NS', name: 'GYFTR' },
{ symbol: 'HAL.NS', name: 'HAL' },
{ symbol: 'HALDER.NS', name: 'HALDER' },
{ symbol: 'HALDYNGL.NS', name: 'HALDYNGL' },
{ symbol: 'HALEOSLABS.NS', name: 'HALEOSLABS' },
{ symbol: 'HAPPSTMNDS.NS', name: 'HAPPSTMNDS' },
{ symbol: 'HAPPYFORGE.NS', name: 'HAPPYFORGE' },
{ symbol: 'HARDWYN.NS', name: 'HARDWYN' },
{ symbol: 'HARIOMPIPE.NS', name: 'HARIOMPIPE' },
{ symbol: 'HARRMALAYA.NS', name: 'HARRMALAYA' },
{ symbol: 'HARSHA.NS', name: 'HARSHA' },
{ symbol: 'HATHWAY.NS', name: 'HATHWAY' },
{ symbol: 'HATSUN.NS', name: 'HATSUN' },
{ symbol: 'HAVELLS.NS', name: 'HAVELLS' },
{ symbol: 'HAVISHA.NS', name: 'HAVISHA' },
{ symbol: 'HAWKINCOOK.NS', name: 'HAWKINCOOK' },
{ symbol: 'HBESD.NS', name: 'HBESD' },
{ symbol: 'HBLENGINE.NS', name: 'HBLENGINE' },
{ symbol: 'HBSL.NS', name: 'HBSL' },
{ symbol: 'HCC.NS', name: 'HCC' },
{ symbol: 'HCG.NS', name: 'HCG' },
{ symbol: 'HCL-INSYS.NS', name: 'HCL-INSYS' },
{ symbol: 'HCLTECH.NS', name: 'HCLTECH' },
{ symbol: 'HDBFS.NS', name: 'HDBFS' },
{ symbol: 'HDFCAMC.NS', name: 'HDFCAMC' },
{ symbol: 'HDFCBANK.NS', name: 'HDFCBANK' },
{ symbol: 'HDFCLIFE.NS', name: 'HDFCLIFE' },
{ symbol: 'HDIL.NS', name: 'HDIL' },
{ symbol: 'HEADSUP.NS', name: 'HEADSUP' },
{ symbol: 'HEALTHX.NS', name: 'HEALTHX' },
{ symbol: 'HECPROJECT.NS', name: 'HECPROJECT' },
{ symbol: 'HEG.NS', name: 'HEG' },
{ symbol: 'HEIDELBERG.NS', name: 'HEIDELBERG' },
{ symbol: 'HEMIPROP.NS', name: 'HEMIPROP' },
{ symbol: 'HERANBA.NS', name: 'HERANBA' },
{ symbol: 'HERITGFOOD.NS', name: 'HERITGFOOD' },
{ symbol: 'HEROMOTOCO.NS', name: 'HEROMOTOCO' },
{ symbol: 'HESTERBIO.NS', name: 'HESTERBIO' },
{ symbol: 'HEXAGON.NS', name: 'HEXAGON' },
{ symbol: 'HEXATRADEX.NS', name: 'HEXATRADEX' },
{ symbol: 'HEXT.NS', name: 'HEXT' },
{ symbol: 'HFCL.NS', name: 'HFCL' },
{ symbol: 'HGINFRA.NS', name: 'HGINFRA' },
{ symbol: 'HGM.NS', name: 'HGM' },
{ symbol: 'HGS.NS', name: 'HGS' },
{ symbol: 'HIKAL.NS', name: 'HIKAL' },
{ symbol: 'HILINFRA.NS', name: 'HILINFRA' },
{ symbol: 'HILTON.NS', name: 'HILTON' },
{ symbol: 'HIMATSEIDE.NS', name: 'HIMATSEIDE' },
{ symbol: 'HINDALCO.NS', name: 'HINDALCO' },
{ symbol: 'HINDCOMPOS.NS', name: 'HINDCOMPOS' },
{ symbol: 'HINDCON.NS', name: 'HINDCON' },
{ symbol: 'HINDCOPPER.NS', name: 'HINDCOPPER' },
{ symbol: 'HINDOILEXP.NS', name: 'HINDOILEXP' },
{ symbol: 'HINDPETRO.NS', name: 'HINDPETRO' },
{ symbol: 'HINDUNILVR.NS', name: 'HINDUNILVR' },
{ symbol: 'HINDWAREAP.NS', name: 'HINDWAREAP' },
{ symbol: 'HINDZINC.NS', name: 'HINDZINC' },
{ symbol: 'HIRECT.NS', name: 'HIRECT' },
{ symbol: 'HISARMETAL.NS', name: 'HISARMETAL' },
{ symbol: 'HITECH.NS', name: 'HITECH' },
{ symbol: 'HITECHCORP.NS', name: 'HITECHCORP' },
{ symbol: 'HITECHGEAR.NS', name: 'HITECHGEAR' },
{ symbol: 'HLEGLAS.NS', name: 'HLEGLAS' },
{ symbol: 'HLVLTD.NS', name: 'HLVLTD' },
{ symbol: 'HMAAGRO.NS', name: 'HMAAGRO' },
{ symbol: 'HMT.NS', name: 'HMT' },
{ symbol: 'HMVL.NS', name: 'HMVL' },
{ symbol: 'HNDFDS.NS', name: 'HNDFDS' },
{ symbol: 'HOMEFIRST.NS', name: 'HOMEFIRST' },
{ symbol: 'HONASA.NS', name: 'HONASA' },
{ symbol: 'HONAUT.NS', name: 'HONAUT' },
{ symbol: 'HONDAPOWER.NS', name: 'HONDAPOWER' },
{ symbol: 'HPAL.NS', name: 'HPAL' },
{ symbol: 'HPIL.NS', name: 'HPIL' },
{ symbol: 'HPL.NS', name: 'HPL' },
{ symbol: 'HSCL.NS', name: 'HSCL' },
{ symbol: 'HTMEDIA.NS', name: 'HTMEDIA' },
{ symbol: 'HUBTOWN.NS', name: 'HUBTOWN' },
{ symbol: 'HUDCO.NS', name: 'HUDCO' },
{ symbol: 'HUHTAMAKI.NS', name: 'HUHTAMAKI' },
{ symbol: 'HYBRIDFIN.NS', name: 'HYBRIDFIN' },
{ symbol: 'HYUNDAI.NS', name: 'HYUNDAI' },
{ symbol: 'IBULLSLTD.NS', name: 'IBULLSLTD' },
{ symbol: 'ICDSLTD.NS', name: 'ICDSLTD' },
{ symbol: 'ICEMAKE.NS', name: 'ICEMAKE' },
{ symbol: 'ICICIAMC.NS', name: 'ICICIAMC' },
{ symbol: 'ICICIBANK.NS', name: 'ICICIBANK' },
{ symbol: 'ICICIGI.NS', name: 'ICICIGI' },
{ symbol: 'ICICIPRULI.NS', name: 'ICICIPRULI' },
{ symbol: 'ICIL.NS', name: 'ICIL' },
{ symbol: 'ICRA.NS', name: 'ICRA' },
{ symbol: 'IDBI.NS', name: 'IDBI' },
{ symbol: 'IDEA.NS', name: 'IDEA' },
{ symbol: 'IDEAFORGE.NS', name: 'IDEAFORGE' },
{ symbol: 'IDFCFIRSTB.NS', name: 'IDFCFIRSTB' },
{ symbol: 'IEX.NS', name: 'IEX' },
{ symbol: 'IFBAGRO.NS', name: 'IFBAGRO' },
{ symbol: 'IFBIND.NS', name: 'IFBIND' },
{ symbol: 'IFCI.NS', name: 'IFCI' },
{ symbol: 'IFGLEXPOR.NS', name: 'IFGLEXPOR' },
{ symbol: 'IGARASHI.NS', name: 'IGARASHI' },
{ symbol: 'IGCL.NS', name: 'IGCL' },
{ symbol: 'IGIL.NS', name: 'IGIL' },
{ symbol: 'IGL.NS', name: 'IGL' },
{ symbol: 'IGPL.NS', name: 'IGPL' },
{ symbol: 'IIFL.NS', name: 'IIFL' },
{ symbol: 'IIFLCAPS.NS', name: 'IIFLCAPS' },
{ symbol: 'IITL.NS', name: 'IITL' },
{ symbol: 'IKIO.NS', name: 'IKIO' },
{ symbol: 'IKS.NS', name: 'IKS' },
{ symbol: 'IL&FSENGG.NS', name: 'IL&FSENGG' },
{ symbol: 'IL&FSTRANS.NS', name: 'IL&FSTRANS' },
{ symbol: 'IMAGICAA.NS', name: 'IMAGICAA' },
{ symbol: 'IMFA.NS', name: 'IMFA' },
{ symbol: 'IMPAL.NS', name: 'IMPAL' },
{ symbol: 'INA.NS', name: 'INA' },
{ symbol: 'INCREDIBLE.NS', name: 'INCREDIBLE' },
{ symbol: 'INDBANK.NS', name: 'INDBANK' },
{ symbol: 'INDGN.NS', name: 'INDGN' },
{ symbol: 'INDHOTEL.NS', name: 'INDHOTEL' },
{ symbol: 'INDIACEM.NS', name: 'INDIACEM' },
{ symbol: 'INDIAGLYCO.NS', name: 'INDIAGLYCO' },
{ symbol: 'INDIAMART.NS', name: 'INDIAMART' },
{ symbol: 'INDIANB.NS', name: 'INDIANB' },
{ symbol: 'INDIANCARD.NS', name: 'INDIANCARD' },
{ symbol: 'INDIANHUME.NS', name: 'INDIANHUME' },
{ symbol: 'INDIASHLTR.NS', name: 'INDIASHLTR' },
{ symbol: 'INDIGO.NS', name: 'INDIGO' },
{ symbol: 'INDIGOPNTS.NS', name: 'INDIGOPNTS' },
{ symbol: 'INDIQUBE.NS', name: 'INDIQUBE' },
{ symbol: 'INDNIPPON.NS', name: 'INDNIPPON' },
{ symbol: 'INDOAMIN.NS', name: 'INDOAMIN' },
{ symbol: 'INDOBORAX.NS', name: 'INDOBORAX' },
{ symbol: 'INDOCO.NS', name: 'INDOCO' },
{ symbol: 'INDOFARM.NS', name: 'INDOFARM' },
{ symbol: 'INDORAMA.NS', name: 'INDORAMA' },
{ symbol: 'INDOSTAR.NS', name: 'INDOSTAR' },
{ symbol: 'INDOTECH.NS', name: 'INDOTECH' },
{ symbol: 'INDOTHAI.NS', name: 'INDOTHAI' },
{ symbol: 'INDOUS.NS', name: 'INDOUS' },
{ symbol: 'INDOWIND.NS', name: 'INDOWIND' },
{ symbol: 'INDPRUD.NS', name: 'INDPRUD' },
{ symbol: 'INDRAMEDCO.NS', name: 'INDRAMEDCO' },
{ symbol: 'INDSWFTLAB.NS', name: 'INDSWFTLAB' },
{ symbol: 'INDTERRAIN.NS', name: 'INDTERRAIN' },
{ symbol: 'INDUSINDBK.NS', name: 'INDUSINDBK' },
{ symbol: 'INDUSTOWER.NS', name: 'INDUSTOWER' },
{ symbol: 'INFOBEAN.NS', name: 'INFOBEAN' },
{ symbol: 'INFOMEDIA.NS', name: 'INFOMEDIA' },
{ symbol: 'INFY.NS', name: 'INFY' },
{ symbol: 'INGERRAND.NS', name: 'INGERRAND' },
{ symbol: 'INNOVACAP.NS', name: 'INNOVACAP' },
{ symbol: 'INNOVANA.NS', name: 'INNOVANA' },
{ symbol: 'INNOVISION.NS', name: 'INNOVISION' },
{ symbol: 'INOXGREEN.NS', name: 'INOXGREEN' },
{ symbol: 'INOXINDIA.NS', name: 'INOXINDIA' },
{ symbol: 'INOXWIND.NS', name: 'INOXWIND' },
{ symbol: 'INSECTICID.NS', name: 'INSECTICID' },
{ symbol: 'INSPIRISYS.NS', name: 'INSPIRISYS' },
{ symbol: 'INTELLECT.NS', name: 'INTELLECT' },
{ symbol: 'INTENTECH.NS', name: 'INTENTECH' }
];

        // Randomly shuffle the massive array
        for (let i = fallbackData.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [fallbackData[i], fallbackData[j]] = [fallbackData[j], fallbackData[i]];
        }

        // Take 40 random stocks to process so the AI always gets a fresh, unique menu
        const randomMenu = fallbackData.slice(0, 40);
        
        const symbolsList = randomMenu.map(item => item.symbol);
        
        let quoteResults = [];
        try {
            // Fetch all 40 quotes in a SINGLE batched request to prevent Yahoo Finance 429 Rate Limiting
            quoteResults = await yahooFinance.quote(symbolsList);
        } catch(e) {
            console.error("Batched Yahoo Quote failed:", e.message);
        }

        const simulatedMovers = [];
        
        for (const item of randomMenu) {
            const quote = quoteResults.find(q => q.symbol === item.symbol);
            if (quote && quote.regularMarketPrice) {
                simulatedMovers.push({
                    symbol: item.symbol,
                    name: item.name,
                    price: quote.regularMarketPrice,
                    changePercent: quote.regularMarketChangePercent || 0
                });
            } else {
                // Final fallback if batch fails for a specific symbol
                const price = await getStockPrice(item.symbol);
                if (price) {
                    simulatedMovers.push({ symbol: item.symbol, name: item.name, price, changePercent: 0 });
                }
            }
        }
        
        simulatedMovers.sort((a,b) => b.changePercent - a.changePercent);
        
        return { 
            gainers: simulatedMovers.slice(0, 15), 
            losers: simulatedMovers.slice(Math.max(simulatedMovers.length - 15, 0)).reverse() 
        };
    }
};

module.exports = { getStockPrice, searchSymbol, getMarketMovers };
