const symbols = [
    'RELIANCE', 'TCS', 'HDFCBANK', 'ICICIBANK', 'INFY', 'ITC', 'SBIN', 'LT', 'BAJFINANCE', 'BHARTIARTL',
    'KOTAKBANK', 'AXISBANK', 'ASIANPAINT', 'HCLTECH', 'MARUTI', 'SUNPHARMA', 'TITAN', 'WIPRO', 'ULTRACEMCO', 'ONGC',
    'NTPC', 'POWERGRID', 'TATASTEEL', 'M&M', 'TATAMOTORS', 'COALINDIA', 'HINDALCO', 'TECHM', 'BAJAJFINSV', 'GRASIM',
    'ADANIENT', 'ADANIPORTS', 'APOLLOHOSP', 'BRITANNIA', 'CIPLA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'HEROMOTOCO', 'HINDUNILVR',
    'INDUSINDBK', 'JSWSTEEL', 'NESTLEIND', 'SBILIFE', 'TATACONSUM', 'UPL', 'BPCL', 'SHREECEM', 'SUZLON', 'IRFC',
    'RVNL', 'IREDA', 'NHPC', 'YESBANK', 'JIOFIN', 'IDEA', 'GMRINFRA', 'PNB', 'BHEL', 'MAZDOCK',
    'HAL', 'BEL', 'RECLTD', 'PFC', 'HUDCO', 'NBCC', 'SJVN', 'ZOMATO', 'OLECTRA', 'ADANIPOWER',
    'TATAPOWER', 'VBL', 'DIXON', 'CDSL', 'BSE', 'ANGELONE', 'KPITTECH', 'TATAELXSI', 'PERSISTENT', 'COFORGE',
    'LTTS', 'LTIM', 'SONACOMS', 'MOTHERSON', 'CAMS', 'AUBANK', 'FEDERALBNK', 'IDFCFIRSTB', 'CHOLAFIN', 'M&MFIN',
    'MANAPPURAM', 'MUTHOOTFIN', 'TVSMOTOR', 'ASHOKLEY', 'ESCORTS', 'AMBUJACEM', 'ACC', 'JINDALSTEL', 'NMDC', 'COCHINSHIP',
    'GRSE', 'BDL', 'BEML', 'MIDHANI', 'ASTRA', 'MTARTECH', 'RAILTEL', 'IRCTC', 'CONCOR', 'TITAGARH',
    'TEXRAIL', 'RITES', 'J&KBANK', 'IOB', 'UCOBANK', 'CENTRALBK', 'BANKINDIA', 'MAHABANK', 'UNIONBANK', 'CANBK',
    'INDIANB', 'PAYTM', 'NYKAA', 'POLICYBKR', 'CARTRADE', 'DELHIVERY', 'EASEMYTRIP', 'HAPPSTMNDS', 'ROUTE', 'TATACHEM',
    'TATACOMM', 'TATAMTRDVR', 'TRENT', 'PAGEIND', 'SRF', 'AARTIIND', 'PIIND', 'COROMANDEL', 'DEEPAKNTR', 'NAVINFLUOR',
    'ATUL', 'ALKYLAMINE', 'BALAMINES', 'LAURUSLABS', 'GRANULES', 'GLENMARK', 'AUROPHARMA', 'LUPIN', 'BIOCON', 'SYNGENE',
    'TORNTPHARM', 'ALKEM', 'IPCALAB', 'JUBILANT', 'APOLLOTYRE', 'MRF', 'CEATLTD', 'BALKRISIND', 'BOSCHLTD', 'ENDURANCE',
    'MINDAIND', 'FLUOROCHEM', 'POLYCAB', 'KEI', 'FINCABLES', 'HAVELLS', 'CROMPTON', 'VOLTAS', 'BLUESTARCO', 'WHIRLPOOL',
    'BATAINDIA', 'RELAXO', 'METROBRAND', 'VEDL', 'HINDZINC', 'NALCO', 'SAIL', 'TATAINVEST', 'BAJAJHLDNG', 'HDFCAMC',
    'UTIAMC', 'MCX', 'IEX', 'CAMPUS', 'MANYAVAR', 'KALYANKJIL', 'TTML', 'TRIDENT', 'WELSPUNIND', 'KPRMILL',
    'VIPIND', 'SYMPHONY', 'TTKPRESTIG', 'HAWKINS', 'AWL', 'ATGL', 'AMARAJABAT', 'EXIDEIND', 'LICI', 'GICRE',
    'NIACL', 'HDFCLIFE', 'ICICIPRULI', 'MAXFIN', 'BANDHANBNK', 'INDIGOPNTS', 'KANSAINER', 'BERGEPAINT', 'SUPREMEIND', 'ASTRAL',
    'FINPIPE', 'PRINCEPIPE', 'VGUARD', 'SYRMA', 'KAYNES', 'AVALON', 'CYIENT', 'ZENSARTECH', 'MPHASIS', 'BSOFT',
    'SONATA', 'INTELLECT', 'TRITURBINE', 'THERMAX', 'CUMMINSIND', 'ABB', 'SIEMENS', 'CGPOWER', 'KEC', 'KALPATPOWR',
    'NCC', 'DILIPBUILD', 'PNCINFRA', 'KNRCON', 'ASHOKA', 'IRB', 'GPPL', 'JSWENERGY', 'TORNTPOWER', 'CESC',
    'IGL', 'MGL', 'GUJGASLTD', 'GSPL', 'PETRONET', 'OIL', 'HINDPETRO', 'CHENNPETRO', 'MRPL', 'GAIL'
];

const uniqueSymbols = [...new Set(symbols)];

let jsArray = '        const fallbackData = [\n';
for (let i = 0; i < uniqueSymbols.length; i += 3) {
    const batch = uniqueSymbols.slice(i, i + 3);
    const line = batch.map(s => `            { symbol: '${s}.NS', name: '${s}' }`).join(', ');
    jsArray += line + (i + 3 < uniqueSymbols.length ? ',' : '') + '\n';
}
jsArray += '        ];';

require('fs').writeFileSync('d:/dsa/trading-bot/backend/scratch/massiveList.txt', jsArray);
console.log('Unique stocks:', uniqueSymbols.length);
